### ISSUE TITLE
KDE NEON not working

### ISSUE THREAD

**Issue by kaynix** [cute-jumper/plasma-rss-indicator#6]
`Error loading QML file: file:///home/kaynix/.local/share/plasma/plasmoids/rss_indicator/contents/ui/main.qml:21:37: Type CompactRepresentation unavailable
file:///home/kaynix/.local/share/plasma/plasmoids/rss_indicator/contents/ui/CompactRepresentation.qml:55:5: Type FullRepresentation unavailable
file:///home/kaynix/.local/share/plasma/plasmoids/rss_indicator/contents/ui/FullRepresentation.qml:2:1: module "QtQuick.LocalStorage" is not installed`

But I do have installed QtQuick.LocalStorage module  5.5 and 5.7 versions

**Comment by cute-jumper** [comment]
I don't use KDE NEON, but from the error message, the problem is indeed caused by the missing localstorage module. Can you do a `locate localstorage | grep QtQuick` to confirm you have `libqmllocalstorageplugin.so` in your system?

**Comment by kaynix** [comment]
Oh, sorry. probably Cause NEON, I've rebooted PC and it working now.
Probably need to go from neon LTS to something stable.
